const MAX_PHOTOS=3;const photos=[];const colors=[['白底','#ffffff'],['蓝底','#cfe4ff'],['粉底','#ffdbe2'],['薄荷绿','#d8f7e9']];
const $=s=>document.querySelector(s);const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)};
function renderPhotos(){const grid=$('#photoGrid');grid.innerHTML=photos.map((p,i)=>`<div class="photo-card"><img src="${p.url}" alt="宠物照片 ${i+1}"><button data-remove="${i}" aria-label="删除">×</button></div>`).join('');$('#uploadBox').style.display=photos.length>=MAX_PHOTOS?'none':'flex'}
$('#photoInput').addEventListener('change',e=>{[...e.target.files].slice(0,MAX_PHOTOS-photos.length).forEach(file=>{if(!file.type.startsWith('image/'))return;photos.push({file,url:URL.createObjectURL(file)})});e.target.value='';renderPhotos()});
$('#photoGrid').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;const i=Number(b.dataset.remove);URL.revokeObjectURL(photos[i].url);photos.splice(i,1);renderPhotos()});
function cropToSquare(img,size,bg='#fff'){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,size,size);const side=Math.min(img.naturalWidth,img.naturalHeight),sx=(img.naturalWidth-side)/2,sy=(img.naturalHeight-side)/2;x.drawImage(img,sx,sy,side,side,0,0,size,size);return c}
function loadImg(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function drawIdCard(img){const c=$('#idCanvas'),x=c.getContext('2d'),name=$('#petName').value.trim()||'毛孩子',species=$('#species').value,age=$('#petAge').value.trim()||'未填写',weight=$('#petWeight').value?`${$('#petWeight').value} kg`:'未填写';x.clearRect(0,0,c.width,c.height);const g=x.createLinearGradient(0,0,900,1200);g.addColorStop(0,'#141922');g.addColorStop(.58,'#1d2430');g.addColorStop(1,'#0d1117');x.fillStyle=g;x.fillRect(0,0,900,1200);x.fillStyle='#6cddb1';x.font='900 50px sans-serif';x.fillText('PawID',64,82);x.fillStyle='#fff';x.font='800 24px sans-serif';x.fillText('毛球身份卡 · PET IDENTITY CARD',66,120);x.fillStyle='#f2c84b';x.font='900 72px sans-serif';x.fillText(name,64,250);x.save();x.beginPath();x.roundRect(64,320,772,520,44);x.clip();const side=Math.min(img.naturalWidth,img.naturalHeight),sx=(img.naturalWidth-side)/2,sy=(img.naturalHeight-side)/2;x.drawImage(img,sx,sy,side,side,64,320,772,520);x.restore();x.fillStyle='#fff';x.font='700 24px sans-serif';x.fillText(`物种  ${species}`,70,920);x.fillText(`年龄  ${age}`,70,970);x.fillText(`体重  ${weight}`,70,1020);x.fillStyle='#9aa8a1';x.font='500 20px sans-serif';x.fillText('品种相似度：等待 AI 视觉模型分析',70,1080);x.fillStyle='#6cddb1';x.font='800 19px sans-serif';x.fillText('喵造实验室 008 · 不是血统证明，仅做外观分析',70,1140)}
async function buildPassports(img){const grid=$('#passportGrid');grid.innerHTML='';for(const [label,bg] of colors){const c=cropToSquare(img,1024,bg);const wrap=document.createElement('div');wrap.className='passport';wrap.append(c);const s=document.createElement('span');s.textContent=label;wrap.append(s);wrap.onclick=()=>{const a=document.createElement('a');a.download=`PawID-${$('#petName').value.trim()||'pet'}-${label}.png`;a.href=c.toDataURL('image/png');a.click()};grid.append(wrap)}}
$('#analyzeBtn').addEventListener('click',async()=>{if(!photos.length){toast('先上传一张毛孩子照片喵');return}const img=await loadImg(photos[0].url);$('#resultPanel').hidden=false;$('#idPanel').hidden=false;$('#passportPanel').hidden=false;drawIdCard(img);await buildPassports(img);$('#resultPanel').scrollIntoView({behavior:'smooth',block:'start'});toast('前端流程已完成，等待接入 AI 视觉模型')});
$('#downloadIdBtn').addEventListener('click',()=>{const a=document.createElement('a');a.download=`PawID-${$('#petName').value.trim()||'pet'}-身份卡.png`;a.href=$('#idCanvas').toDataURL('image/png');a.click()});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
